name: Build and Publish Stringer NuGet Package with Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu:24-04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install essential tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore Stringer.Nuget/Stringer.Nuget.sln

      - name: Build the solution
        run: dotnet build Stringer.Nuget/Stringer.Nuget.sln --configuration Release --no-restore

      - name: Run NUnit Tests
        working-directory: Stringer.Nuget.Tests
        run: dotnet test Stringer.Nuget.Tests/Stringer.Nuget.Tests.csproj --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"

      - name: Publish Test Results
        uses: actions/upload-artifact@v3
        with:
          name: nunit-test-results
          path: Stringer.Nuget.Tests/TestResults/test-results.trx

      - name: Ensure nupkg directory exists
        run: mkdir -p ./nupkg

      - name: Pack the project
        working-directory: Stringer.Nuget
        run: |
          dotnet pack Stringer.Nuget/Stringer.Nuget.csproj --configuration Release --output ./nupkg
          find . -name "*.nupkg"

      - name: Debug package output
        run: find . -name "*.nupkg" || echo "No packages found"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.NUGET_KEY }}

      - name: Publish package to GitHub Packages
        run: dotnet nuget push ./Stringer.Nuget/nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.NUGET_KEY }} --skip-duplicate

      - name: Upload NuGet package artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: ./nupkg/*.nupkg
